### ISSUE TITLE
To parallelize or not to parallelize

### ISSUE THREAD

**Issue by Kimonili** [Ankur-Deka/Emergent-Multiagent-Strategies#1]
Hi authors,

Congratulations for your work. I took a quick glance in your repo and saw that you did not use the multiprocessing module. So this means that one agent takes action after the other using a for loop? 

In addition, again if I understood correct, each agent has its own networks, and shares information with its teammates. Is that correct?

Thank you in advance!

**Comment by Ankur-Deka** [comment]
Hi

Thank you and sorry for the late reply, I hadn't noticed your message. 
1) We collect the the actions of all agents and then synchronously take step in the environment using all the actions. 
2) In theory, all agents could have different networks with copies of the same parameters during test time. However, to keep our implementation simple we use the same network within one team. Within a team, the same network is used to process observations of each agent and information is shared. Different teams - guards and attackers have different networks and don't share information.

I hope this clarifies.
